update 0.10.3
AnacondaRecipes/pathspec-feedstock pull request #3
Opened 2023-01-10 23:04 UTC by avasomething

Changelog:
- bump version, checksum
- cleaned up and fixed broken tests
- updated dependencies
- added `build/skip`

2023-01-10 23:05 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_afyxlmkzqi/clone/recipe/meta.yaml:37: missing_pip_check: For pypi packages, pip check should be present in the test commands
ERROR: /tmp/abs_afyxlmkzqi/clone/recipe/meta.yaml:37: missing_pip_check: For pypi packages, pip check should be present in the test commands
WARNING: /tmp/abs_afyxlmkzqi/clone/recipe/meta.yaml:52: missing_license_url: The recipe is missing a license_url
Errors were found

</details>

2023-01-11 16:02 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_47_e7li814/clone/recipe/meta.yaml:37: missing_pip_check: For pypi packages, pip check should be present in the test commands
ERROR: /tmp/abs_47_e7li814/clone/recipe/meta.yaml:37: missing_pip_check: For pypi packages, pip check should be present in the test commands
WARNING: /tmp/abs_47_e7li814/clone/recipe/meta.yaml:52: missing_license_url: The recipe is missing a license_url
Errors were found

</details>

2023-01-11 22:43 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_f57sdb0oul/clone/recipe/meta.yaml:37: missing_pip_check: For pypi packages, pip check should be present in the test commands
ERROR: /tmp/abs_f57sdb0oul/clone/recipe/meta.yaml:37: missing_pip_check: For pypi packages, pip check should be present in the test commands
WARNING: /tmp/abs_f57sdb0oul/clone/recipe/meta.yaml:52: missing_license_url: The recipe is missing a license_url
Errors were found

</details>

2023-01-11 23:18 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_7bbliy0vop/clone/recipe/meta.yaml:37: missing_pip_check: For pypi packages, pip check should be present in the test commands
ERROR: /tmp/abs_7bbliy0vop/clone/recipe/meta.yaml:37: missing_pip_check: For pypi packages, pip check should be present in the test commands
WARNING: /tmp/abs_7bbliy0vop/clone/recipe/meta.yaml:52: missing_license_url: The recipe is missing a license_url
Errors were found

</details>

2023-01-11 23:25 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_8761g5m0v6/clone/recipe/meta.yaml:37: missing_pip_check: For pypi packages, pip check should be present in the test commands
ERROR: /tmp/abs_8761g5m0v6/clone/recipe/meta.yaml:37: missing_pip_check: For pypi packages, pip check should be present in the test commands
WARNING: /tmp/abs_8761g5m0v6/clone/recipe/meta.yaml:52: missing_license_url: The recipe is missing a license_url
Errors were found

</details>

2023-01-11 23:52 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_c1kleh3r1t/clone/recipe/meta.yaml:37: missing_pip_check: For pypi packages, pip check should be present in the test commands
ERROR: /tmp/abs_c1kleh3r1t/clone/recipe/meta.yaml:37: missing_pip_check: For pypi packages, pip check should be present in the test commands
WARNING: /tmp/abs_c1kleh3r1t/clone/recipe/meta.yaml:52: missing_license_url: The recipe is missing a license_url
Errors were found

</details>

2023-01-12 00:03 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_2egnn33qbw/clone/recipe/meta.yaml:37: missing_pip_check: For pypi packages, pip check should be present in the test commands
ERROR: /tmp/abs_2egnn33qbw/clone/recipe/meta.yaml:37: missing_pip_check: For pypi packages, pip check should be present in the test commands
WARNING: /tmp/abs_2egnn33qbw/clone/recipe/meta.yaml:52: missing_license_url: The recipe is missing a license_url
Errors were found

</details>

2023-01-12 00:14 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_5fn7j5qqdc/clone/recipe/meta.yaml:37: missing_pip_check: For pypi packages, pip check should be present in the test commands
ERROR: /tmp/abs_5fn7j5qqdc/clone/recipe/meta.yaml:37: missing_pip_check: For pypi packages, pip check should be present in the test commands
WARNING: /tmp/abs_5fn7j5qqdc/clone/recipe/meta.yaml:52: missing_license_url: The recipe is missing a license_url
Errors were found

</details>

2023-01-12 00:25 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_dapq1vl6kp/clone/recipe/meta.yaml:37: missing_pip_check: For pypi packages, pip check should be present in the test commands
ERROR: /tmp/abs_dapq1vl6kp/clone/recipe/meta.yaml:37: missing_pip_check: For pypi packages, pip check should be present in the test commands
WARNING: /tmp/abs_dapq1vl6kp/clone/recipe/meta.yaml:52: missing_license_url: The recipe is missing a license_url
Errors were found

</details>

2023-01-12 00:59 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_b54ncz9c6w/clone/recipe/meta.yaml:36: missing_pip_check: For pypi packages, pip check should be present in the test commands
ERROR: /tmp/abs_b54ncz9c6w/clone/recipe/meta.yaml:36: missing_pip_check: For pypi packages, pip check should be present in the test commands
WARNING: /tmp/abs_b54ncz9c6w/clone/recipe/meta.yaml:51: missing_license_url: The recipe is missing a license_url
Errors were found

</details>

2023-01-12 16:33 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_2az6qhsxoh/clone/recipe/meta.yaml:36: missing_pip_check: For pypi packages, pip check should be present in the test commands
ERROR: /tmp/abs_2az6qhsxoh/clone/recipe/meta.yaml:36: missing_pip_check: For pypi packages, pip check should be present in the test commands
WARNING: /tmp/abs_2az6qhsxoh/clone/recipe/meta.yaml:51: missing_license_url: The recipe is missing a license_url
Errors were found

</details>

2023-01-12 20:16 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_00eb_v8hml/clone/recipe/meta.yaml:38: missing_pip_check: For pypi packages, pip check should be present in the test commands
ERROR: /tmp/abs_00eb_v8hml/clone/recipe/meta.yaml:38: missing_pip_check: For pypi packages, pip check should be present in the test commands
WARNING: /tmp/abs_00eb_v8hml/clone/recipe/meta.yaml:53: missing_license_url: The recipe is missing a license_url
Errors were found

</details>

2023-01-12 21:45 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_43k4zjbkk3/clone/recipe/meta.yaml:38: missing_pip_check: For pypi packages, pip check should be present in the test commands
ERROR: /tmp/abs_43k4zjbkk3/clone/recipe/meta.yaml:38: missing_pip_check: For pypi packages, pip check should be present in the test commands
WARNING: /tmp/abs_43k4zjbkk3/clone/recipe/meta.yaml:53: missing_license_url: The recipe is missing a license_url
Errors were found

</details>

2023-01-12 21:47 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_c9llomunyh/clone/recipe/meta.yaml:38: missing_pip_check: For pypi packages, pip check should be present in the test commands
ERROR: /tmp/abs_c9llomunyh/clone/recipe/meta.yaml:38: missing_pip_check: For pypi packages, pip check should be present in the test commands
WARNING: /tmp/abs_c9llomunyh/clone/recipe/meta.yaml:53: missing_license_url: The recipe is missing a license_url
Errors were found

</details>

2023-01-12 22:51 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_4elmohpxe2/clone/recipe/meta.yaml:38: missing_pip_check: For pypi packages, pip check should be present in the test commands
ERROR: /tmp/abs_4elmohpxe2/clone/recipe/meta.yaml:38: missing_pip_check: For pypi packages, pip check should be present in the test commands
WARNING: /tmp/abs_4elmohpxe2/clone/recipe/meta.yaml:53: missing_license_url: The recipe is missing a license_url
Errors were found

</details>

2023-01-20 00:00 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_51zmhfhh_a/clone/recipe/meta.yaml:38: missing_pip_check: For pypi packages, pip check should be present in the test commands
ERROR: /tmp/abs_51zmhfhh_a/clone/recipe/meta.yaml:38: missing_pip_check: For pypi packages, pip check should be present in the test commands
WARNING: /tmp/abs_51zmhfhh_a/clone/recipe/meta.yaml:53: missing_license_url: The recipe is missing a license_url
Errors were found

</details>

2023-01-25 00:50 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_db_bkc8a8z/clone/recipe/meta.yaml:40: missing_pip_check: For pypi packages, pip check should be present in the test commands
ERROR: /tmp/abs_db_bkc8a8z/clone/recipe/meta.yaml:40: missing_pip_check: For pypi packages, pip check should be present in the test commands
WARNING: /tmp/abs_db_bkc8a8z/clone/recipe/meta.yaml:55: documentation_overspecified: Using doc_url and doc_source_url is overspecified
Errors were found

</details>

2023-01-25 00:58 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_23e0u10ek3/clone/recipe/meta.yaml:31: missing_test_requirement_pip: pip is required in the test requirements.
WARNING: /tmp/abs_23e0u10ek3/clone/recipe/meta.yaml:56: documentation_overspecified: Using doc_url and doc_source_url is overspecified
Errors were found

</details>

2023-01-25 01:02 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_6dr7r_jvl4/clone/recipe/meta.yaml:31: missing_test_requirement_pip: pip is required in the test requirements.
WARNING: /tmp/abs_6dr7r_jvl4/clone/recipe/meta.yaml:56: documentation_overspecified: Using doc_url and doc_source_url is overspecified
Errors were found

</details>

2023-01-25 01:07 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_b4purmr682/clone/recipe/meta.yaml:31: missing_test_requirement_pip: pip is required in the test requirements.
WARNING: /tmp/abs_b4purmr682/clone/recipe/meta.yaml:56: documentation_overspecified: Using doc_url and doc_source_url is overspecified
Errors were found

</details>

2023-01-25 01:18 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_c0masm3wv2/clone/recipe/meta.yaml:31: missing_test_requirement_pip: pip is required in the test requirements.
WARNING: /tmp/abs_c0masm3wv2/clone/recipe/meta.yaml:56: documentation_overspecified: Using doc_url and doc_source_url is overspecified
Errors were found

</details>

2023-01-25 01:58 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_f6td5j8j6h/clone/recipe/meta.yaml:42: missing_pip_check: For pypi packages, pip check should be present in the test commands
ERROR: /tmp/abs_f6td5j8j6h/clone/recipe/meta.yaml:42: missing_pip_check: For pypi packages, pip check should be present in the test commands
WARNING: /tmp/abs_f6td5j8j6h/clone/recipe/meta.yaml:57: documentation_overspecified: Using doc_url and doc_source_url is overspecified
Errors were found

</details>

2023-01-25 02:08 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_e2t9vqcxz1/clone/recipe/meta.yaml:32: missing_test_requirement_pip: pip is required in the test requirements.
WARNING: /tmp/abs_e2t9vqcxz1/clone/recipe/meta.yaml:57: documentation_overspecified: Using doc_url and doc_source_url is overspecified
Errors were found

</details>

2023-01-25 02:54 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_49sl_xdoov/clone/recipe/meta.yaml:58: documentation_overspecified: Using doc_url and doc_source_url is overspecified
Warnings were found

</details>

2023-01-25 07:09 UTC, katietz requested changes
beside this, fine.

2023-01-25 07:09 UTC, katietz commented on recipe/meta.yaml
> -    - pytest --pyargs pathspec -k "not test_2_1_check_realpath and not test_2_4_recursive_links and not test_2_5_recursive_circular_links"  # [win]
I would add here a ' || cmd /K "exit /b 0"' to this line, so check on Windows is not causing a build failure.  And move comments up.

2023-01-25 09:04 UTC, danpetry commented on recipe/meta.yaml
> -    - pytest --pyargs pathspec -k "not test_2_1_check_realpath and not test_2_4_recursive_links and not test_2_5_recursive_circular_links"  # [win]
The test passes on Windows btw

2023-01-25 15:56 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_1728rjm_42/clone/recipe/meta.yaml:53: documentation_overspecified: Using doc_url and doc_source_url is overspecified
Warnings were found

</details>

2023-01-25 16:12 UTC, danpetry approved these changes
Nice work, thanks!

2023-01-25 20:34 UTC, ELundby45 approved these changes
LGTM!

2023-01-25 21:18 UTC, merged

2023-01-25 21:19 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_147aytqqe9/clone/recipe/meta.yaml:53: documentation_overspecified: Using doc_url and doc_source_url is overspecified
Warnings were found

</details>